### ISSUE TITLE
Wrong BeautifulSoup4 dependency

### ISSUE THREAD

**Issue by jm-rivera** [lpicci96/imf-reader#1]
https://github.com/lpicci96/imf-reader/blob/206e2d257a9714e2f3898a0909779a99a1e3dd43/pyproject.toml#L13C1-L13C15

Should be: https://pypi.org/project/beautifulsoup4/

Instead you've added a dummy package: https://pypi.org/project/bs4/

**Comment by lpicci96** [comment]
Thanks for catching that. I updated the the dependencies in the last commit
